TEMPLATE = subdirs

SUBDIRS += \
	ACM_ICPC_Team \
	AlternatingCharacters \
	AngryProfessor \
	AppenAandDelete \
	AppleAndOrange \
	BeautifulBinaryString \
	BeautifulDaysAtTheMovies \
	BeautifulTriplets \
	BetweenTwoSets \
	BigSorting \
	BillDivision \
	BreakingTheRecords \
	CaesarCipher \
	CamelCase \
	CatsAndMouse \
	CavityMap \
	ChocolateFeast \
	CircularArrayRotation \
	CutTheSticks \
	DayOfTheProgrammer \
	DesignerPDViewer \
	DivisibleSumPairs \
	DrawingBook \
	ElectronicsShop \
	EqualizeTheArray \
	FairRations \
	FindDigits \
	FlatlandSpaceStations \
	FunnyString \
	Gemstones \
	GradingStudents \
	HackerRankInString \
	HalloweenSale \
	HappyLadybugs \
	IntroToTutorialChallenges \
	JumpingOnTheCloudsRevisited \
	LibraryFine \
	LisasWorkbook \
	ManasaAndStones \
	MarsExploration \
	MigratoryBirds \
	MinimumDistances \
	ModifiedKaprekarNumbers \
	NumberLineJumps \
	PickingNumbers \
	Quicksort_1_Partition \
	SaveThePrisoner \
	SeparateTheNumbers \
	SequenceEquation \
	ServiceLane \
	SherlockAndSquares \
	StrangeCounter \
	StrongPassword \
	SubArrayDivision \
	SuperReducedString \
	TaumAndBday \
	TheHurdleRace \
	TwoCharacters \
	UtopianTree \
	ViralAdvertising \
	WeightedUniformStrings
