TEMPLATE = subdirs

SUBDIRS += \
	ACM_ICPC_Team \
	AngryProfessor \
	AppenAandDelete \
	AppleAndOrange \
	BeautifulDaysAtTheMovies \
	BeautifulTriplets \
	BetweenTwoSets \
	BillDivision \
	BreakingTheRecords \
	CamelCase \
	CatsAndMouse \
	CavityMap \
	ChocolateFeast \
	CircularArrayRotation \
	CutTheSticks \
	DayOfTheProgrammer \
	DesignerPDViewer \
	DivisibleSumPairs \
	DrawingBook \
	ElectronicsShop \
	EqualizeTheArray \
	FairRations \
	FindDigits \
	FlatlandSpaceStations \
	GradingStudents \
	HalloweenSale \
	HappyLadybugs \
	IntroToTutorialChallenges \
	JumpingOnTheCloudsRevisited \
	LibraryFine \
	LisasWorkbook \
	ManasaAndStones \
	MigratoryBirds \
	MinimumDistances \
	ModifiedKaprekarNumbers \
	NumberLineJumps \
	PickingNumbers \
	SaveThePrisoner \
	SequenceEquation \
	ServiceLane \
	SherlockAndSquares \
	StrangeCounter \
	SubArrayDivision \
	TaumAndBday \
	TheHurdleRace \
	UtopianTree \
	ViralAdvertising
